### ISSUE TITLE
cmake should pick up gcc, gfortran in PATH, not the one in /usr/bin

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#10]
a chunk from cmake log
```
  The Fortran compiler:

    /usr/bin/gfortran

  and the C compiler:

    /usr/bin/cc

  failed to compile a simple test project using both languages.  The output
```

however, this is my gfortran
```
$ which gfortran
/home/case/bin/gfortran
```

**Comment by multiplemonomials** [comment]
Are you setting the `COMPILER` option?

**Comment by hainm** [comment]
No I don't.

**Comment by hainm** [comment]
may be raise Error if not setting it?

**Comment by hainm** [comment]
```
$ ./configure 

Your AMBERHOME environment variable is not set! Auto set it to: 
/home/haichit/amber_git/amber

Usage: ./configure [flags] compiler

    where compiler is one of: [[ gnu, intel, pgi, clang, or cray ]]
```

**Comment by multiplemonomials** [comment]
The `COMPILER` variable is meant to be the equivalent of the final argument to the configure script.  If you do not set it, then I allow CMake to pick "default" compilers.  I don't have any control over which compilers it picks.  If you want old-configure-script-like behavior, then set `COMPILER` to what you would have passed to the configure script.

I made it this way because on some platforms (e.g. Visual Studio, or some oddball UNIX), you actually want to use CMake's default compilers, or set compilers manually (through `CMAKE_C_COMPILER` etc.).  If there is a general consensus that letting CMake choose compilers is a bad default, then I could do what you said and require users to set `COMPILER`.

**Comment by hainm** [comment]
In my case here, all of compilers are GNU ones. Adding "-DCOMPILER=gnu" will fix the issue. Seems confusing to me.

What do you define "default" here?

**Comment by multiplemonomials** [comment]
Sorry but I can't really change that behavior.  CMake just seems to prefer the compilers in `/usr/bin`.

By default, `COMPILER` will be set to `auto`.  This causes Amber's build script to let CMake choose whatever compilers it wants.  I refer to the CMake-chosen compilers as the "default" ones.

**Comment by hainm** [comment]
> Sorry but I can't really change that behavior.

so just force user to specify compiler option. I don't feel "auto" is good enough. Many users don't have experience to debug and sometimes they ask very simple question in amber list.

**Comment by tluchko** [comment]
I ran into this yesterday when I tried to use cmake for the first time in a long time.  I agree with @hainm that the auto behavior can cause unexpected problems that may be difficult to diagnose. On my Mac, cmake picked up Apple's CLANG for the C and C++ compilers and the version of gfortran I had loaded with MacPorts. On Stampede2 I explicitly loaded GNU 7.1 using the environment module but cmake picked up GNU 4.8 instead. The only reason I picked up on this is because I was already having problems and watching the output carefully.

IMO, if the default can't be changed then I think that the compile option should be required. Users on less common platforms, like Visual Studio or some oddball UNIX, will then need set things manually.

**Comment by multiplemonomials** [comment]
Alright, I'll use the same convention for this as I did on the `DOWNLOAD_MINICONDA` variable, where it will stop the build until you set it one way or the other.

**Comment by multiplemonomials** [comment]
OK, this has now been added to commit 2dd02c53b7.  Now, you get the following when you first run CMake:

```
 Error: Please select the compiler you want Amber to use by setting the COMPILER CMake vairable to one of the below:
--
                       Supported Amber compilers:
                 -------------------------------------------------------------------------
  COMPILER value | C executable | C++ executable | Fortran executable |   tested versions
  ----------------------------------------------------------------------------------------
      GNU        |     gcc      |      g++       |     gfortran       |   4.4.7, 4.8.4 +
      INTEL      |     icc      |      icpc      |     ifort          |   12 - 17
      PGI        |     pgcc     |      pgc++     |     pgf90          |   14.9, 15.4, 16.5
      CLANG      |     clang    |      clang++   |     gfortran       |
      CRAY       |     cc       |      CC        |     ftn            |   8.4.6*
  ----------------------------------------------------------------------------------------
      AUTO       |   <uses the default CMake-chosen compilers>
      MANUAL     |   <uses the CC, CXX, and FC environment variables, or the
                         CMAKE_<LANGUAGE>_COMPILER CMake variables>

--
CMake Error at cmake/AmberCompilerConfig.cmake:44 (message):
  Amber cannot build until COMPILER is set properly.
```
Hope this reduces some of the unexpected surprises.

Hai, you will probably have to update your CMake CI job to change the COMPILER value to uppercase.
