### ISSUE TITLE
fftw3.f: No such file or directory

### ISSUE THREAD

**Issue by tluchko** [Amber-MD/cmake-buildscripts#111]
When building on CentOS 6.6 with GNU and Intel compilers, I get the error message

`
/home/software/Downloads/amber18/src/pmemd.gem/src/fft1d.F90:41: error: fftw3.f: No such file or directory
`

I happens whether or not I use `-DFORCE_INTERNAL_LIBS=fftw`.

I have no problems on MacOS with the GNU compilers.

Log files are attached.
[errorreport.tar.gz](https://github.com/Amber-MD/cmake-buildscripts/files/1877211/errorreport.tar.gz)

**Comment by tluchko** [comment]
BTW, a workaround would be to disable `pmemd.gem`, but it seems that only AmberTools targets can be disabled. My impression, looking at `WhichTools.cmake` is that Amber targets could be added but this may require a lot of work and testing.

**Comment by multiplemonomials** [comment]
Hmm OK I did a bit of research.  It looks like `amber18/src/pmemd.gem/src/fft1d.F90` is trying to include a header that doesn't actually exist anywhere in its source folder, but is included with a systemwide install of FFTW.  So, it works on most of our dev systems, but not ones without FFTW installed.  The error only shows up when MKL is active (since it tries to use `MKL_FFT`), so a workaround would be `-DFORCE_DISABLE_TOOLS=mkl`.  I'm going to email David right now about what this should be including.

Sorry about not responding until now, this PR kind of fell through the cracks.

**Comment by multiplemonomials** [comment]
Just got an email from David, he's fixed this in master.
