### ISSUE TITLE
Arpack link test result is not used

### ISSUE THREAD

**Issue by dacase** [Amber-MD/cmake-buildscripts#113]
Short summary:

In the master branch, cmake is using g++ to create libcpptraj, but is not adding a -lgfortran argument, (or using gfortran to do the linking) so all needed gfortran links are un-resolved.  Bug report attached.
[errorreport.tar.gz](https://github.com/Amber-MD/cmake-buildscripts/files/1920706/errorreport.tar.gz)

**Comment by multiplemonomials** [comment]
Your problem still seems to be that it's picking up a version of Arpack that is built for a different runtime library.

```
/home/casegroup/amber18/lib/libarpack.a(dsaupd.o):dsaupd.f:(.text+0x39f): more undefined references to `_gfortran_transfer_integer_write' follow
```

Actually, looks like CMake caught this:
```
-- The ARPACK library was found, but /home/casegroup/amber18/lib/libarpack.a is not linkable.  Perhaps it was built with an incompatible Fortran compiler? Please set ARPACK_LIBRARY to point to a working ARPACK library. (missing:  ARPACK_IS_LINKABLE) 
```

**Comment by multiplemonomials** [comment]
OK looks like this is just because I forgot to change the if statement to use the result of that check: https://github.com/Amber-MD/cmake-buildscripts/blob/d1e7585d0033db1640ed71047aa61230bf0bf8c2/3rdPartyTools.cmake#L363

I'll get a fix out as soon as I can (though it's the end of the semester here so it might take a while)

**Comment by dacase** [comment]
This is completely weird to me.  The message:

The ARPACK library was found, but /home/casegroup/amber18/lib/libarpack.a is not linkable.

suggests that cmake is looking everywhere on the disk for libarpack.a.  The build directory is in /home/case/amber_git/build, but cmake seems to be finding something in some other users' (or pseudo-users') home directory.  Surely this is not what one really wants to be doing(?).  Among other things, these files are on a 12 TB partition, which right now happens to be nearly empty.  But surely one doesn't want the build system to be searching through enormous numbers of files just in hopes of finding an existling libarpack;  recompiling only takes a few seconds.

[Second, I don't understand the "different runtime library" argument: there is only one compiler that is ever user (either in /home/case or in /home/casegroup).  That is, there is only one version of gfortran on this machine, so how can different runtime libraries be involved?]

**Comment by multiplemonomials** [comment]
CMake searches a large variety of paths for libraries.  It uses a fairly sane order of precedence, but anything on your PATH or in any system directory is fair game.  The exact search order is documented here: https://cmake.org/cmake/help/v3.11/command/find_library.html

This is actually part of the reason I made the whole `PRINT_PACKAGING_REPORT` thing: so that it's easier to see the libraries that CMake has found. 

Also, FWIW, the "not linkable" error message is actually a custom error printed from my code here: https://github.com/Amber-MD/cmake-buildscripts/blob/master/FindARPACK.cmake

CMake doesn't actually check linkability unless you write code telling it to.

**Comment by multiplemonomials** [comment]
Also, CMake does not search for libraries recursively, so that can't be how it found that `libarpack`.  My guess is that that directory is in your environment somehow.

**Comment by dacase** [comment]
OK: I have to remember to set my PATH to a minimal set before running cmake: that way it won't find other libraries or miniconda installations.
