### ISSUE TITLE
RPATH issues with libraries in nonstandard directories

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#119]
On Linux, we really need to add the Miniconda/Anaconda lib directory to the RPATH in the path script.  THis has become a problem with the new change that enables use of link libraries from internal Miniconda.

**Comment by dacase** [comment]
Is this related to the fact that CMake is also searching the miniconda/anaconda directory tree for include files?  The latter is giving me problems, as described in Issue ???.

**Comment by multiplemonomials** [comment]
Somewhat, yeah.  A while back I enabled CMake to search the Miniconda tree for libraries, but there are clearly still a few issues coming how they handle RPATHs.  The main reason I did this is that now, by using Miniconda's bundled MKL, it's possible to build Amber with MKL without having to install MKL beforehand.  This seems like a big advantage, at least to me.

**Comment by dacase** [comment]
OK, but the X11 include problem (#122) is kind of a showstopper for me, since it breaks the standard build.  I've been super busy lately, so just put this on the shelf for now.  But it keeps me from (easily) testing cmake builds in (say) the rism-cleanup branch, where I am building rism codes in a new way.
Is there a way I could edit the X11_INCLUDE_DIRS variable after running cmake but before running make?

**Comment by multiplemonomials** [comment]
Yes, actually.  Great idea!  Per [the FindX11 documentation](https://cmake.org/cmake/help/v3.12/module/FindX11.html) you can just pass the `-DX11_INCLUDE_DIR=<dir>` argument to CMake.

**Comment by multiplemonomials** [comment]
Should now be fixed in Amber master!
