### ISSUE TITLE
cuda 9.2

### ISSUE THREAD

**Issue by DrDomenicoMarson** [Amber-MD/cmake-buildscripts#127]
Hello everyone,

I'm compiling AMBER on a cluster, and having failed with the standard "./configure" procedure, I gave cmake3 a try! I loved this new possibility, and I'm glad you are implementing it!

I successfully compiled the serial version of the code (unfortunately only with make -j 1), but when I tried the final compilation (serial+MPI+cuda) I found some error on the cuda part, that i think are of general interest.

1. in $AMBERHOME/cmake/CudaConfig.cmake
   only up to cuda 9.1 is recognised, but compilation should not have problems with at least cuda 9.2 (I had to change the line 62 to recognise my 9.2 installation).

2. with CUDA enabled, cmake tries to "load" a non-existing directory "$AMBERHOME/src/gpu_utils".
I tried to modify $AMBERHOME/src/CMakeLists.txt, commenting line 4 (#add_subdirectory(gpu_utils))

The compilations than stops at around 95 % with this error:
```
amber18/src/pmemd/src/cuda/kNLCPNE.h(924): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(long long, long long)"
            function "min(long long, unsigned long long)"
            function "min(float, float)"
            function "min(double, float)"
            argument types are: (PMEForce, PMEFloat)
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00003e95_00000000-11_kCalculatePMENonbondEnergy.compute_61.cpp1.ii".
```

Could you help me understanding this error?
I'm attaching the errorreport.tar.gz with all the log informations!
[errorreport.tar.gz](https://github.com/Amber-MD/cmake-buildscripts/files/2562541/errorreport.tar.gz)

Thank you for your time,
Domenico

**Comment by multiplemonomials** [comment]
Hmm, are you using Amber from Git, or the Amber18 release?

**Comment by multiplemonomials** [comment]
Actually never mind, I can infer from the line numbers that it's the git version.  

Anyway, taking a look at this, some searching turns up this declaration (in gputypes.h):
```cpp
#if defined(use_DPFP)
typedef double             __align(8)  PMEFloat;
typedef double             __align(8)  PMEForce;
typedef double             __align(8)  PMEEnergy;
typedef double             __align(8)  PMEVirial;
typedef double2            __align(16) PMEDouble2;
typedef double4            __align(32) PMEDouble4;
typedef double2            __align(16) PMEFloat2;
typedef double4            __align(16) PMEFloat4;
typedef cufftDoubleComplex __align(16) PMEComplex;
#elif defined(use_SPFP)
typedef long long int      __align(8)  PMEForce;
typedef long long int      __align(8)  PMEEnergy;
typedef long long int      __align(8)  PMEVirial;
typedef float                          PMEFloat;
typedef double2            __align(16) PMEDouble2;
typedef double4            __align(32) PMEDouble4;
typedef float2 __align(8)  PMEFloat2;
typedef float4 __align(16) PMEFloat4;
typedef cufftComplex PMEComplex;
#endif
```
We can also see that the error message is that min() is being called as `(PMEForce, PMEFloat)`, and that the possible overloads are 
```
function "min(long long, long long)"
function "min(long long, unsigned long long)"
function "min(float, float)"
function "min(double, float)"
```
The compiler is trying to pick one of these overloads, but all are inexact matches so it can't decide.

Now, we don't know whether it was the SPFP or the DPFP version that caused the error (both get built around the same time), but we _can_ figure it out.  For DPFP we end up calling `min(double, double)`, and for SPFP we have `min(long long int, float)`.  So, since "long long" appears in the list of overloads, I bet it's the second one.  

Since the second parameter to min is a constant, fixing this should actually be pretty simple: we just have to make sure the constant has the same type as the value it's compared to.  So, change line 924 from

```cpp
        shFx = max((PMEFloat)-10000.0, min(shFx, (PMEFloat)10000.0));
```
to
```cpp
        shFx = max((PMEForce)-10000.0, min(shFx, (PMEForce)10000.0));
```

You may have to do the same to other places this error pops up, but I really think this will fix it.

**Comment by sizmailov** [comment]
I'm unable to build `pmemd` with GPU support via cmake (Amber18+AmberTools18). Regular `./configure`-base build works fine. 

```bash
(cd build ; cmake .. -DCOMPILER=GNU -DDOWNLOAD_MINICONDA=FALSE -DBUILD_PYTHON=FALSE -DCHECK_UPDATES=FALSE -DAPPLY_UPDATES=FALSE -DCUDA=TRUE )
```

I get the following errors:
```
CMake Error at AmberTools/src/CMakeLists.txt:15 (add_subdirectory):
  add_subdirectory given source "chamber" which is not an existing directory.


CMake Error at AmberTools/src/CMakeLists.txt:15 (add_subdirectory):
  add_subdirectory given source "nabc" which is not an existing directory.


CMake Error at src/CMakeLists.txt:4 (add_subdirectory):
  add_subdirectory given source "gpu_utils" which is not an existing
  directory.
```
