### ISSUE TITLE
pack amber

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#23]
I am not not sure how you will do that and how user should expect after clicking to icon to install.

Ideally, all amber-relates files/folder should in the same tree amber17/{...}.
There are some packages that distribute in different location and I don't think that's a good idea for amber to follow that.

Feel free to close this if you already do similiar thing.

**Comment by multiplemonomials** [comment]
Alright, I finished the doc page: http://ambermd.org/pmwiki/index.php/Main/CMake-Creating-Packages

Since I'm about to rewrite much of the packaging code, I decided to document what I'm going to make, not what currently exists.  As such, some of the functionality in that page exists only in the `cmake` branch, or not at all.

**Comment by multiplemonomials** [comment]
As of merge of experimental to master, the documentation is now complete
