### ISSUE TITLE
Error: Could not compile and run programs with NetCDF Fortran interface.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#8]
Please see all the attached files.

[log_print.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1202144/log_print.txt)

[CMakeCache.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1202146/CMakeCache.txt)

[CMakeError.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1202148/CMakeError.txt)

[CMakeOutput.txt](https://github.com/Amber-MD/CMakeConfigScripts/files/1202149/CMakeOutput.txt)

**Comment by hainm** [comment]
I am using centos:5 based docker image

```bash
docker run -it --rm ambermd/amber-build-box bash
```

**Comment by multiplemonomials** [comment]
Relevant section of CMakeError.txt
```
Fatal Error: Cannot read module file 'netcdf.mod' opened at (1), because it was created by a different version of GNU Fortran
```

It looks like something is wrong with the system `netcdf-fortran`.  You can run CMake with `-DFORCE_INTERNAL_LIBS=netcdf-fortran` to fix this.  I should probably make it so that it will default to internal netcdf-fortran if this test fails, huh.

**Comment by hainm** [comment]
We should use internal version as default
Can not assume user's version is good.
That's why we always want user use Miniconda python because we know it
works well.

And that's why we include some 3rd party packages.
Hai

**Comment by multiplemonomials** [comment]
I am going to have to disagree with you there.  Isn't it kind of the Linux mindset to have each package use libraries from other packages?  Building everything internally is space- and time-inefficient, and it can create problems if our libraries conflict with the system's versions.  As long as CMake can test that the system libraries work, then I think that we should use as many of them as we can.  If the users have broken system libraries on their machines, then that's their problem, not ours.  

In this case, though, the NetCDF-Fortran check is kind of broken, and I'll fix it when I get a chance.  It should have automatically fallen back to internal netcdf-fortran when the check failed.

**Comment by hainm** [comment]
> Isn't it kind of the Linux mindset to have each package use libraries from other packages?

How can you test different platforms, different version (API might change), different Linux distribution? Technically I would agree with you but testing and maintenance are not easy.

>  If the users have broken system libraries on their machines, then that's their problem, not ours.

nah. It's out problem. Especially if they spent money to buy your software.

**Comment by agoetz** [comment]
In this case the NetCDF-Fortran check fails and it should revert to the internal version (that's what I see in log_print.txt).

In general I agree that we should use system libraries if they are available. Take BLAS and LAPACK, these work since decades. I don't recall why the opposite decision was made for netcdf, i.e. to use the system version only if the user asks for it. I silently assume there is a good reason, we may want to ask Dan Roe, I think he added netcdf support.

Down the road we want a stable build system - we don't have the bandwidth to cope with users flooding the Amber mailing list with build problems. Hence going for a stable solution.

**Comment by swails** [comment]
I agree with @multiplemonomials here -- a system library should be preferred over internal ones whenever practical.  Python is an exception to the rule since it is a comparably fast-changing language standard that has severe deficiencies with many aspects of the Amber development/build model.  We go with the Miniconda approach simply because it's (surprisingly) easier and more reliable than using the system Python.  By contrast, we've never built or released a standalone perl distribution with the various perl codes we have because perl doesn't have those same deficiencies (and obviously the same for shells).

Fortran is the main impediment here.  The whole concept of how Fortran modules are implemented makes creating portable binary distributions impossible.  For NetCDF (and FFTW3 with RISM, I believe), the Fortran interface is implemented through a compiled Fortran .mod file.  The issue with these is their fragility -- they must be built with the exact compiler that is used to build the Fortran code they're being linked with.  This is never seen in the C/C++ world where you can link against virtually any library you can find.

That's why NetCDF is a challenge here -- if the system NetCDF was built with GCC 5.0, you must then build Amber with exactly the same compiler or you will get the error:

```
Fatal Error: Cannot read module file 'netcdf.mod' opened at (1), because it was created by a different version of GNU Fortran
```

So what the current Amber configure script does is check that a "hello world" program can be compiled with `use netcdf`, and if that compilation fails it falls back on building its own NetCDF-Fortran with the same compilers used to build the rest of our Fortran codes.

As for why the configure script only takes system libraries when explicitly told to, that's because originally it *never* had the option of using system libraries.  And once I got the build system to work with system NetCDF, I didn't bother putting in the extra time needed to implement looking in standard default locations for those libraries.

I still think it makes sense to look for any library we use in the system (and verify it works for us) before falling back to building our own.

**Comment by swails** [comment]
> Isn't it kind of the Linux mindset to have each package use libraries from other packages?
> How can you test different platforms, different version (API might change), different Linux distribution? Technically I would agree with you but testing and maintenance are not easy.

The way this is done in the field is to have a set of "supported" Linux operating systems and then say "it might work for others, but it's untested".  That's done everywhere -- like CUDA for instance.


> If the users have broken system libraries on their machines, then that's their problem, not ours.
> nah. It's our problem. Especially if they spent money to buy your software.

There are aspects of both here.  Our build system is so quirky that we bear some responsibility.  However, it's not our responsibility to support a broken or insufficient system.  What if their compilers are broken?  What if one of the libraries we depend on but *don't* provide (like flex, or csh, or patch, or ...) don't work?  Or what if they have a weird `LD_LIBRARY_PATH` set that injects broken libraries into the search path before ones that work?  Users absolutely have a responsibility to have a "working" system.  Our responsibility lies in ensuring that users can install Amber in a straightforward manner if they haven't broken their system and that they do not have to bend over backwards to adapt to our quirks.

**Comment by swails** [comment]
For instance, the NetCDF-Fortran error here is our responsibility -- this error is indicative of supporting/suggesting compilers that are not native to a system and depending on a library that *must* be built with that same compiler.  MPI is another example of exactly this restriction.  So we should have something in place that makes working around that easy for the user.

**Comment by drroe** [comment]
> I don't recall why the opposite decision was made for netcdf, i.e. to use the system version only if the user asks for it.

Jason covered this pretty well. I also recall that there were issues on certain platforms with the packaged NetCDF libraries. For example, at one point the packaged NetCDF libraries for Fedora were broken for a while and would cause segfaults with cpptraj.

I think it can be nice to both have bundled versions of important or hard-to-find/build libraries and have the option to point to a user-specified one. The benefits of providing libraries like NetCDF ourselves is it makes testing and debugging simpler. The downside is that we can miss out on things like platform-specific optimizations, which is why having the option to point to an external one is nice as well.

Somewhat off-topic: one library where I would really like the external option is FFTW.  I've always also hated that the bundled version of FFTW rebuilds itself every time whether it needs to or not.

**Comment by multiplemonomials** [comment]
OK, since there are issues with the system netcdf on certain platforms, I will have the CMake script use internal netcdf unless explicitly told to use an external one.    I'll also make it fail gracefully when using external netcdf if the module file is broken.  I will keep the rest of the libraries defaulting to external.

Also, @drroe I completely rewrote fftw's build system in CMake, so that won't be a problem anymore
